### ISSUE TITLE
Why not YAML for defining the entries?

### ISSUE THREAD

**Issue by bdarcus** [tomncooper/pandoc-gls#6]
Just wondering (and sorry if I missed something; I only briefly looked) as I'm thinking about glossaries in org-mode, why not use YAML, since it's used elsewhere in the pandoc universe?

```yaml
title: my animal glossary
entries:
    horse:
        name: horse
        description: a four-legged animal
```
